Feat/communication
dholubeu/driver-service pull request #6
Opened 2024-02-29 13:45 UTC by dholubeu

2024-03-04 13:55 UTC, AbandonedScope requested changes

2024-03-04 13:55 UTC, AbandonedScope commented on src/main/java/com/dholubeu/driverservice/domain/Driver.java
> +    }
Выноси

2024-03-04 13:55 UTC, AbandonedScope commented on src/main/java/com/dholubeu/driverservice/kafka/KfConsumerImpl.java
> +                //TODO add consumers groups
Добавил?

2024-03-04 13:55 UTC, AbandonedScope commented on src/main/java/com/dholubeu/driverservice/service/impl/CarServiceImpl.java
> +    public static final String RESOURCE_DOES_NOT_EXIST_BY_ID_MESSAGE = "Car with id %d does not exist";
Это можно вынести в отдельный класс с константами для сообщений

2024-03-04 13:55 UTC, AbandonedScope commented on src/main/java/com/dholubeu/driverservice/service/impl/CarServiceImpl.java
> +                        String.format(RESOURCE_DOES_NOT_EXIST_BY_ID_MESSAGE, id)));
```suggestion
        return carRepository.findById(id)
                .orElseThrow(() -> new ResourceDoesNotExistException(
                        String.format(RESOURCE_DOES_NOT_EXIST_BY_ID_MESSAGE, id)));
```

2024-03-04 13:55 UTC, AbandonedScope commented on src/main/java/com/dholubeu/driverservice/web/controller/DriverController.java
> +        return driverMapper.toDto(driver);
Маппинг должен происходить в сервисах, а не контроллерах

2024-03-04 13:55 UTC, AbandonedScope commented on src/main/java/com/dholubeu/driverservice/web/controller/ApiControllerAdvice.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
HttpStatus.CONFLICT

2024-03-06 09:52 UTC, dholubeu commented on src/main/java/com/dholubeu/driverservice/kafka/KfConsumerImpl.java
> +                //TODO add consumers groups
нет, решил оставить в последнюю очередь, так как там и дополнительный сервис создавать придется. Рабочая реализация кафки есть, если будет время, посижу над этим

2024-03-06 09:53 UTC, dholubeu commented on src/main/java/com/dholubeu/driverservice/service/impl/CarServiceImpl.java
> +    public static final String RESOURCE_DOES_NOT_EXIST_BY_ID_MESSAGE = "Car with id %d does not exist";
эти константы актуальны только для этого класса

2024-03-06 09:53 UTC, dholubeu commented on src/main/java/com/dholubeu/driverservice/web/controller/DriverController.java
> +        return driverMapper.toDto(driver);
почему, это же логика именно web слоя, в сервис отправляем уже сущность

2024-03-06 12:10 UTC, AbandonedScope commented on src/main/java/com/dholubeu/driverservice/web/controller/DriverController.java
> +        return driverMapper.toDto(driver);
Вот именно, что это логика, вся логика должна находится в сервисах, у контроллеров только одна задача - принять запрос перенаправляя его на сервисы

2024-03-25 13:21 UTC, AbandonedScope approved these changes

2024-03-25 13:49 UTC, merged